modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="kryptadium"
version="0.0.5"
displayName="Kryptadium 1.20.1"
credits="Infinitumcraft And SkyFox Made This Mod"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="SkyFox and Infinitumcraft"
description="The Kryptadium Mod"

[[dependencies.kryptadium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.kryptadium]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

